server:
  port: 8004

spring:
  application:
    name: oapi-oauthprovider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oapi?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    allow-bean-definition-overriding: true
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
