server:
  port: 8002

spring:
  application:
    name: oapi-msgprovider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oapi?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
#sql\u8BED\u53E5\u4F7F\u7528\u6CE8\u89E3\uFF0C\u4E0D\u7528\u914Dmybatis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/